# 开发环境配置
server:
   # 服务器的HTTP端口，默认为80
   port: 8088
   servlet:
       # 应用的访问路径
       context-path: /
#    tomcat:
#        # tomcat的URI编码
#        uri-encoding: UTF-8
#        # tomcat最大线程数，默认为200
#        max-threads: 800
#        # Tomcat启动初始化的线程数，默认值25
#        min-spare-threads: 30

system:
    dbName: nutsdemo  #一定要配置，默认数据库
    modelPackage: com.jiadao.model


# 日志配置
logging:
  level:
    org.nutz: debug
    com.jiadao: info
    org.springframework: warn

# 数据源配置
spring:
    http: 
        encoding:
            charset: UTF-8
            enabled: true
            #uri-encoding: UTF-8
        #converters:
            #preferred-json-mapper:    
    devtools:
        restart:
            enabled: true
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        #driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            url: jdbc:mysql://localhost:3306/nutsdemo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useInformationSchema=true
            username: root
            password: root
            remarks: true #设置jdbc可以获取remarks信息 
            useInformationSchema: true #设置jdbc可以获取remarks信息 
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: 
                login-password: 
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

    
    jackson: 
    #参数意义：
        #JsonInclude.Include.ALWAYS       默认
        #JsonInclude.Include.NON_DEFAULT   属性为默认值不序列化
        #JsonInclude.Include.NON_EMPTY     属性为 空（””） 或者为 NULL 都不序列化
        #JsonInclude.Include.NON_NULL      属性为NULL  不序列化
        default-property-inclusion: ALWAYS
        time-zone: GMT+8
        #全局日期json格式化
        date-format: yyyy-MM-dd HH:mm:ss
    
    
    
    # Spring Boot 整合 Activiti 报错 [processes/] 不存在
    activiti:
        check-process-definitions: false
        # 检测身份信息表是否存在
        db-identity-used: false